### PR TITLE
DateInput Fixes (Fixes #1293)

### LINKED ISSUE #1293: DateInput:  When enableTextInput=false clicking on month or year immediately closes popup

### PR DESCRIPTION
**Pull request by lbwexler**
+ Fix issue with click closing popup immediately when enableTextInput= false
+ Fix issue with focus blur not closing popup
+ Fix issue with keyboard events not being consumed and doing multiple actions
 e.g. causing parent scrolling after opening up menu via up/down

Hoist P/R Checklist
-------------------
Review and check off the below. Items that do not apply should be checked to indicate they have been considered. If unclear if a step is relevant, please leave unchecked and note in comments.

- [ X] Up to date with `develop` branch as of last change.
- [ X] Ready for review (or add `wip` label).
- [ X] Added CHANGELOG entry (or N/A)
- [X ] Checked for breaking changes (add `breaking-change` label + CHANGELOG if so, or N/A)
- [ X] Updated doc comments / prop-types (or N/A)
- [ N/A] Reviewed and tested on Mobile (or N/A)
- [ N/A] Created Toolbox branch / PR (link provided here, or N/A)

> **Pull request reviewers:** when merging this P/R, please consider using a *squash commit* to collapse multiple intermediate commits into a single commit representing the overall feature change. This helps keep the commit log clean and easy to scan across releases.

### CODE REVIEW

File: desktop/cmp/input/DateInput.js [hunk 1]
```diff
@@ -215,30 +215,32 @@ export class DateInput extends HoistInput {
             inputHasFocus = this.containsElement(activeEl);
 
         if (!popoverHasFocus && !inputHasFocus) {
+            this.setPopoverOpen(false);
```
Comment (amcclain) [inline desktop/cmp/input/DateInput.js]: This change appears to be breaking the actual flushing of a just-clicked value from the popover into the control.  Need to investigate further....

**Comment by lbwexler** [comment]
whackamole continues -- think I have a solution here

**Comment by lbwexler** [comment]
Think this addresses the regression and also adds an additional bit of polish to avoid losing the keyboard focus when the popover is taken down.
